### ISSUE TITLE
Test d'acceptation

### ISSUE THREAD

**Issue by jeanpierrethach** [LAHTTE/Sim1-LAHTTE#14]
# Germe : 63, Montant initial : 100$

Le cas pour la dame de coeur pourrait être un typo puisque la carte vaut toujours 37.
Selon la méthode laCouleur, elle vaudrait plutôt un trèfle (couleur = 2) 

À moins que l'arrangement des couleurs, i.e. 0 : coeur, 1 : carreau, 2 : trefle, 3 : pique
est un bogue. Mais, j'en doute puisque le reste du test d'acceptation émis sur Moodle fonctionne à part cette carte.

Si on changerait l'arrangement pour que le trèfle donne un coeur, i.e. 0 : trefle, 1 : carreau, 2 : coeur, 3 : pique, cela affectera pour la majorité d'entre eux, les autres couleurs du test d'acceptation.

**Comment by bphoul00** [comment]
J'ai juste essayé d'exécuter le logiciel sans notre modification, et il nous a donné la même carte dans notre propre logiciel. 

Donc je croix aussi c'est un typo.
