### ISSUE TITLE
Le montant ne diminue pas lorsque le joueur perd, mais augmente

### ISSUE THREAD

**Issue by odlaner** [LAHTTE/Sim1-LAHTTE#17]
plus préciesment regarder le switch

**Comment by jeanpierrethach** [comment]
Dans le but de comprendre le problème, pourrais-tu décrire un scénario qui montre que le montant ne diminue pas lorsque le joueur perd, mais qui augmente.

**Comment by odlaner** [comment]
Probleme regler
